spring:



  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect




#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create


  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672 }
    username: ${RABBITMQ_USERNAME:guest }
    password: ${RABBITMQ_PASSWORD:guest}
    virtual_host: ${RABBITMQ_USERNAME:guest }
    connection_timeout: 30000
rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  info:
    env:
      enabled: true

  health:
    circuitbreakers:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
info:
  app:
    name: JobApplication
    description: Job app built by EmbarkX
    version: 1.0.0
logging:
  level:
    org.springframework.amqp.rabbit: DEBUG

server:
  port: 8083

app:
  message: "Hello all"

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

build:
  version: order1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost



 #circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: count_based

#retry mechanism
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 5s
#
#ratelimiter
  ratelimiter:
    instances:
      rateBreaker:
        timeout-duration: 0
        limit-refresh-period: 4s
        limit-for-period: 2
