
spring:

  data:
    mongodb:
     uri: ${URL}
     database: ecommerce
#  datasource:
#    url: jdbc:postgresql://localhost:5432/user
#    username: AASHISH
#    password: AASHISH
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#      console:
#        enabled: true
#  datasource:
#      url: jdbc:h2:mem:test
#  jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: create

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  main:
    allow-bean-definition-overriding: true

server:
    port: 8081
build:
  version: user3

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

