spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: classpath:/config
server:
  port: 8888
  rabbitmq:
    host:
      port: 5672
      username: guest
      password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"